name: GitHub Actions Demo
on: push
jobs:
  check-os-version:
    runs-on: ubuntu-latest
    steps:
      - run: uname -v
  build-and-execute-helloworld:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: gcc helloworld.c
      - run: ./a.out
